### ISSUE TITLE
"EMI Calculator" für Berechnungen in EMI+ Update der EMI Zusammenfassung 

### ISSUE THREAD

**Issue by Jaaaaaaaan** [fsr/Stoffkiste#11]
https://github.com/XPhantomad/EMI_Calculator zum eventuellen hinzufügen in die Stoffkiste

**Comment by niklaskeerl** [comment]
Hallo @Jaaaaaaaan ,
cool, dass ihr die Zusammenfassung erweitert habt und auch eigene Tools entwickelt habt! :)

Hier nun ein paar Fragen und Lösungsvorschläge, damit wir das einfach in die Stoffkiste einpflegen können:

1) Der eigentliche EMI_Calculator befindet sich im Ordner [Programm](https://github.com/XPhantomad/EMI_Calculator/tree/master/Programm) oder? Und die executable für Windows ist dann [project1.exe](https://github.com/XPhantomad/EMI_Calculator/blob/master/Programm/project1.exe)? Ich denke das einfachste wäre hier von der Stoffkiste aus auf die Windows Binary und Quellcode zu verlinken.
2) Bitte beim Fano C-Programm noch einen Hinweis hinzufügen, wo genau ihr das her habt, dann können wir das genauso wie beim EMI_Calculator machen und darauf verlinken bzw. auch die Quelldatei hier hochladen mit Kompilieranleitung bzw. makefile.
3) Für das Huffman Eingabetool gibt es mehrere Dateien. Das AutoHotKey Skript und eine Windows Executable. Ist in der [Huffman.exe](https://github.com/XPhantomad/EMI_Calculator/blob/master/Huffman.exe) einfach nur das Skript und das AutoHotKey Programm gebundelt oder ist da was anderes drin?
4) Ihr habt relativ viel gelöscht in der Zusammenfassung, wenn ich das richtig gesehen habe. Kam das alles dieses Jahr nicht dran oder habt ihr für euch da einfach einen anderen Fokus gesetzt? Wäre hilfreich zu wissen um eine Entscheidung für die kommenden Semester treffen zu können.

Viel Erfolg in der Prüfungszeit weiterhin :)

**Comment by Jaaaaaaaan** [comment]
Hallo Niklas,

1. Ganz genau, die Windows exe vom Rechner ist project1.exe - wie man den Rechner am besten verfügbar macht weiß ich ehrlich gesagt nicht, eine frei verfügbare Möglichkeit um das ganze zum kompilieren wäre [Lazarus](https://www.lazarus-ide.org/)

2. Der Code stammt von hier: [http://cppgm.blogspot.com/2008/01/shano-fano-code.html](http://cppgm.blogspot.com/2008/01/shano-fano-code.html), wir haben nur ein paar Zeilen verändert damit das ganze von Visual Studio kompiliert werden kann

3. Die Huffman.exe ist nur das ausführbare AHK skript

4. Bestimmte Punkte wie HTML kamen dieses Semester komplett nicht dran, die haben wir einfach noch aus der alten Zusammenfassung übernommen. Was wir verändert haben sind nur die Themen die bei uns behandelt wurden, und bei denen sind wir schon auf alle Schwerpunkte eingegangen und haben keinen bestimmten Fokus gesetzt.
Ich denke dabei waren wir nicht so nah an der Vorlesung und haben eher versucht, alles für die Prüfung schnell greifbar zu machen. Und natürlich ist es möglich, dass diese Themen in anderen Semestern detaillierter behandelt werden 

Auch dir erfolgreiche Prüfungen!
