### ISSUE TITLE
RA TrikSheet Fehler?

### ISSUE THREAD

**Issue by CaroDD** [fsr/Stoffkiste#12]
In der PDF Triksheet ist mMn ein Fehler.
Bei destination routing sagt c=0, dass der obere Ausgang gewählt wird. Das Bild geht jedoch auf den unteren Ausgang. Bei c=1 genau umgekehrt.
In meinen Augen wurde lediglich die Grafik vertauscht.

**Comment by therealr5** [comment]
Fixed in 191fcf7
