### ISSUE TITLE
Biete weitere Zusammenfassungen an

### ISSUE THREAD

**Issue by xXSkyWalkerXx1** [fsr/Stoffkiste#19]
[Datenbanken_Zsfg.pdf](https://github.com/fsr/Stoffkiste/files/11178808/Datenbanken_Zsfg.pdf)
Aus SS2022

[Softwaretechnologie_2_Zsfg.pdf](https://github.com/fsr/Stoffkiste/files/11178812/Softwaretechnologie_2_Zsfg.pdf)
Aus WS2022/23
Hinweiß: Das ist eher eine Ausarbeitung der Prüfungsthemen, beinhaltet also nicht die gesamte Vorlesung.

[Mensch_Computer_Interaktion_Zsfg.pdf](https://github.com/fsr/Stoffkiste/files/11178814/Mensch_Computer_Interaktion_Zsfg.pdf)
Aus WS2022/23
Hinweiß: Das ist eher eine Ausarbeitung der Prüfungsthemen, beinhaltet also nicht die gesamte Vorlesung. (Hier lohnt es sich u.a. nochmal mit den Veränderungen zu befassen, was also alles passiert, wenn ich bspw. auf einem Canvas zeichne. Hab da jetzt nich mehr genau die Prüfungsfrage im Kopf, ging aber in diese Richtung.)

[Formale_Systeme_Zsfg.pdf](https://github.com/fsr/Stoffkiste/files/11178826/Formale_Systeme_Zsfg.pdf)
Aus SS2022

**Comment by therealr5** [comment]
Hi. ganz vielen Dank für die Zusammenfassungen. Hab sie mal hinzugefügt :)
