### ISSUE TITLE
Zusammenfasung Rechnernetze

### ISSUE THREAD

**Issue by sgeisler** [fsr/Stoffkiste#3]
@chlewe und ich haben eine [Rechnernetzezusammenfassung](https://github.com/sgeisler/rechnernetze/) geschrieben. Ich würde die gerne zur Stoffkiste beisteuern, jedoch wäre es cool wenn man weiterhin nur das .tex-File eincheckt und die PDF per CI bauen lässt (wie momentan in meinem Repo).

@sebschrader schlug vor gleich für das gesamte Repo alle .tex-Files zu kompilieren und als Github Page zu veröffentlichen (also auch noch einen Index bauen). Wenn ihr das gut findet würde ich mal das CI-Script zurechtbasteln und einen Pull-Request aufmachen.

**Comment by Feliix42** [comment]
Klar, klingt nach einer super Idee! Nur zu :)

**Comment by sebschrader** [comment]
Ich hab euch beide zum Team der Stoffkiste hinzugefügt und einen neuen `ed25519` SSH-Key als Deploy-Key eingerichtet.
